#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width	0
bspc config window_gap		10
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on

nitrogen --restore &

$HOME/.config/polybar/launch.sh

picom --no-startup-id picom  -b --config ~/.config/picom/picom.conf 

/usr/lib/polkit-kde-authentication-agent-1 &

xinput --set-prop 'SYNA3296:00 06CB:CD50 Touchpad' "libinput Natural Scrolling Enabled" 1
